version: '3'

services:
  postgres:
    image: postgres:13
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=reserve_trust
      - APP_DB_PASS=foo
      - APP_DB_NAME=fibonacci
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    #ports:
      #- 5432:5432

  fibonacci:
    image: reserve_trust_application
    ports:
      - 8080:8080
